---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          - --errors-only
          - --disable=import-error

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.2
    hooks:
      - id: check-metaschema
        files: ^.+/schema/.*schema\.json$
